### ISSUE TITLE
It is recommended to add Tencent DOH and DOT

### ISSUE THREAD

**Issue by Silentely** [paulmillr/encrypted-dns#1]
First of all, thank you very much for the description file. It is recommended to add Tencent DOH and DOT. The DOH address is https://doh.pub/dns-query, and the DOT address is dns.pub or doh.pub

**Comment by paulmillr** [comment]
Feel free to submit a pull request.

**Comment by Silentely** [comment]
> Feel free to submit a pull request.

I tried to edit the dns address and IP according to your template, but the alibabadns description file will be overwritten after downloading and installing.

**Comment by Silentely** [comment]
> 随时提交请求请求。

Resolved, request submitted
