### ISSUE TITLE
BlahDNS Switzerland DoH

### ISSUE THREAD

**Issue by certuna** [paulmillr/encrypted-dns#100]
BlahDNS also has a Swiss DoH server, not just a DoT server - could you add this profile?

https://doh-ch.blahdns.com/dns-query
IPv4: 45.91.92.121 (same as DoT)
IPv6: 2a0e:dc0:6:23::2

**Comment by paulmillr** [comment]
You can do it by yourself.

**Comment by certuna** [comment]
How do I generate the correct UUIDs?

**Comment by certuna** [comment]
ah ok, will write one and issue a PR
