### ISSUE TITLE
Unable to remove Cloudflare DNS over TLS from DNS list on iPhone

### ISSUE THREAD

**Issue by JSTee787** [paulmillr/encrypted-dns#112]
I was experimenting with the Cloudflare DNS over TLS profile on my iPhone 11 Pro Max with IOS 15.6.

After attempting to remove the profile, the DNS remained in the DNS list. I suspect this is an iPhone bug, but thought I'd mention it here, I have seen vague mentions of it elsewhere.

I subsequently added the profile again, and it was named "Cloudflare DNS over TLS 1" and this time this instance could be removed using the remove profile option.

Any suggestions to remove it other than restoring my phone from a backup?

**Comment by paulmillr** [comment]
we don't prohibit removing it, so not sure what happens here. there's a specific flag to allow removal in every config.
