### ISSUE TITLE
Not working with ios16

### ISSUE THREAD

**Issue by PrinzEric** [paulmillr/encrypted-dns#114]
Hy there, the Config Profile isn‘t working with iOS 16 in cellular mode.
Checked with quad9

**Comment by Who-42** [comment]
i have ios 16 on a 13Pro and my 3 config profiles are working 
checked with dnsleaktest

**Comment by PrinzEric** [comment]
Restart on 16.1 fixed and Quad9 Show IPS - WoodyNet.

**Comment by bearz314** [comment]
Hi, I'm on MacOS Ventura 13.0.1. Unfortunately the profile I tested (cloudflare-https) did not work. DNS still shows up in Wireshark.

Sidenotes:
- 1.1.1.1/help is not a reliable way of testing this.
- unsure if dnsleaktest actually tests for eDNS. Probably just testing for an unexpected IP without active MITM-ing.
