### ISSUE TITLE
Iranian Community 

### ISSUE THREAD

**Issue by Elnazzakeri** [paulmillr/encrypted-dns#115]
According to recent news in Iran we cannot connect to any server of this app. To be a voice of our country to the world against violence.

**Comment by nasiralamreeki** [comment]
This isn't an app these are profiles to use encrypted dns with a variety of different dns providers.

**Comment by Elnazzakeri** [comment]
So can you 

> This isn't an app these are profiles to use encrypted dns with a variety of different dns providers.

So can you show me how can I solve my issues and connect to appvpn??
