### ISSUE TITLE
Documented install instructions differ with latest macOS release

### ISSUE THREAD

**Issue by sambacha** [paulmillr/encrypted-dns#117]
## macOS 13 (Ventura) changes to profile installs 

Safari no longer will load the configuration directly into your Settings, in fact you can not even save it as a non `.txt` file, you have to download it from shell/somewhere else to preserve the ext of the file. 

You can however run the  following shell command to open up the correct menu for loading the profile:

```console
alice@macbook:~$ open x-apple.systempreferences:com.apple.Profiles-Settings.extension
```

This means you can both download the profile and load the settings window to install it via shell

### Installing the profile 
1. Choose Apple menu  > System Settings, click Privacy and Security in the sidebar, then click Profiles on the right. (You may need to scroll down.
 > You may be asked to supply your password or other information during installation.
2. In the Downloaded section, double-click the profile.
3. Review the profile contents then click Continue, Install or Enroll to install the profile.
> If an earlier version of a profile is already installed on your Mac, the settings in the updated version replace the previous ones.

### Support for 'Signed Profiles' 
Additionally, support for signing these profiles has been added, here is an example of the install modal:

![](https://d.pr/i/0IXOcK.jpeg)

### References from macOS user manual 
[macOS 13 Configuration profile settings](https://support.apple.com/guide/mac-help/configuration-profiles-standardize-settings-mh35561/13.0/mac/13.0)

[macOS 10.15 Catalina Configuration profile settings](https://support.apple.com/guide/mac-help/configuration-profiles-standardize-settings-mh35561/10.15/mac/10.15)

## Issue

Wat do with README instructions ser?

**Comment by paulmillr** [comment]
Thanks, added to readme. I don't see a support for signing a profile on your screenshot.  It says install / ignore / cancel - no "sign" button.
