### ISSUE TITLE
New Dns

### ISSUE THREAD

**Issue by icyrusyt** [paulmillr/encrypted-dns#139]
Please add new dns because we gamers need this dns very much, please spare your time for us gamers.

![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/c810331f-e29b-47d5-8e4c-0cf46842715a)
![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/6bd0adfe-e47a-468c-8546-fe8829d6bc7a)

**Comment by paulmillr** [comment]
send a pull request by yourself

**Comment by icyrusyt** [comment]
> send a pull request by yourself
![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/d5b5ed22-d55b-45cc-8f44-6109bbe6d132)
![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/5b2edaea-d706-450e-8610-8517185ce900)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/b679e9fc-e26b-436c-![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/43141b0a-6024-45bd-be9a-15c6d375849b)b250-2e6e6131563e)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/7ddfdf4c-e3dc-4295-ac9e-dc3877cf328f)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/e4dd3154-f7b6-46c4-8f29-c8b77829762c)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/fb97b71c-ef48-4801-a045-7fcc76537de6)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/70f4e92e-af20-46a6-9757-fbc357554040)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/69c51164-34bb-4032-af9a-7516668bb517)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/bf9ee1cc-a97a-4660-9d79-05facd122560)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/e111c79d-1745-44ef-8b79-c251f86e66b3)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/fd5d705d-7dab-4b5c-a13c-bb9408a094b3)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/a47214d5-8044-4130-bc03-7e68308a7998)![image](https://github.com/paulmillr/encrypted-dns/assets/140291461/33b1b421-8a3e-4bed-88cc-53b2b82942d2)
