### ISSUE TITLE
/etc/resolver configuration not working

### ISSUE THREAD

**Issue by mssio** [paulmillr/encrypted-dns#14]
When this profile is enabled on my mac, this configuration file in /etc/resolver/docker is not working:

    #/etc/resolver/docker
    
    nameserver 127.0.0.1
    port 19322 

Are there any change can I make in the profile to make it works?

**Comment by paulmillr** [comment]
seems like a docker issue

**Comment by mssio** [comment]
No man, this is not docker issue, this is OS related issue.
That configuration just tell the OS to use my docker container as a resolver for anything *.docker domain.
If I uninstall the profile, everything works normally.

**Comment by paulmillr** [comment]
yeah, but not much we can do. If you think it's a bug, try reporting to Apple directly. I just created a bunch of profiles, that's it

**Comment by chew-z** [comment]
> So macOS does not read this configuration (/etc/resolver/docker) anymore because the dns profile is installed.

You are attempting to split DNS queries. /etc/resolver is not supposed to work with DOH/DNS-over-TLS mobileconfigs but you can still achieve just that. 

Read [Apple Documentation](https://developer.apple.com/documentation/devicemanagement/dnssettings/ondemandruleselement).

And for creating profile I would recommend using [imazing Profile Editor](https://apps.apple.com/app/imazing-profile-editor/id1487860882?ls=1&mt=12)

Still Apple Documentation is cryptic and not user friendly.

**Comment by mssio** [comment]
@chew-z thanks for your help. I have tried few options tinkering with onDemandRules but still can't make it work. Do you have working example on this one?
