### ISSUE TITLE
Can’t install two different profiles

### ISSUE THREAD

**Issue by antispy1605** [paulmillr/encrypted-dns#156]
I first downloaded the cloudflare no malware profile. Then downloaded the quad9 profile but it replaced the previous one

**Comment by zecanard** [comment]
@nhlghost Just edit the .mobileconfig files and make the `PayloadIdentifier` and `PayloadUUID` fields unique. Then you can install several profiles and switch between them easily. On macOS, open a Terminal session and enter `uuidgen` to generate a new UUID. The `PayloadIdentifier` can be whatever you want.

Or check out this post for a repository that has already done this:
https://github.com/paulmillr/encrypted-dns/issues/29#issuecomment-804020684
