### ISSUE TITLE
I am the DNS

### ISSUE THREAD

**Issue by Potterli20** [paulmillr/encrypted-dns#2]
Hello author, I would like to ask how to get the signature, I also want to get DNS, purr purr.

**Comment by paulmillr** [comment]
Which signature?

**Comment by Potterli20** [comment]
> Which signature?

Ios  14 private DNS signature😂

**Comment by paulmillr** [comment]
Just adjust the profile config file to your needs. Change IPs and server url. The files are in text format.

The encrypted api is public & official.
