### ISSUE TITLE
Hope to add Tencent DoH configuration profiles

### ISSUE THREAD

**Issue by SebastianMMC** [paulmillr/encrypted-dns#20]
DoH: https://doh.pub/dns-query
DoT: dns.pub

**Comment by paulmillr** [comment]
@luoqz9 edit the files, they are in ttext format,  should be easy to add new file

**Comment by luoqz9** [comment]
Feel sorry about that. But later I found out that DNSPod （in your project）had been acquired by Tencent and used by Tencent now. By the way, all publicly registered DNS in China are tainted by Chinese government requirements. We have to use a special solution.

**Comment by BirdInFire** [comment]
@luoqz9 yeah I know about that, it just I do not do anything that can push non Chinese user to use Chinese services to protect us non Chinese from Chinese censorship, If a Chinese ask me in private I will help him to connect himself securely but that all.

**Comment by jackjyq** [comment]
shall close this issue because DNSPod has already been added

https://raw.githubusercontent.com/paulmillr/encrypted-dns/master/profiles/dnspod-https.mobileconfig
