### ISSUE TITLE
[question] iPadOS support

### ISSUE THREAD

**Issue by kcris** [paulmillr/encrypted-dns#24]
Hi,
any idea if this could work in iPadOS, and not just iOS?
There is no Profile section under Settings/General in iPadOS 14.3
thanks

**Comment by paulmillr** [comment]
it works fine on ipad, i've tested

**Comment by kcris** [comment]
indeed, it works on iPadOS, thanks :)

I was initially puzzled since I couldn't find the Profile section on my iPad

turns out that the Profile section is only available after downloading/installing a profile
