### ISSUE TITLE
CloudFlare for team 

### ISSUE THREAD

**Issue by lowrisk75** [paulmillr/encrypted-dns#30]
I used your main config for [Cloudflare](https://raw.githubusercontent.com/paulmillr/encrypted-dns/master/cloudflare-https.mobileconfig)

and I tried to change the IP's for Cloudflare team instead of Cloudflare public IPs.
I installed the profile on iOS 14.5, query are resolved but somehow not filtered 

(I have a block list on Cloudflare for team and I can access blocked domain) 

im not sure what Im missing

**Comment by paulmillr** [comment]
make sure to change ServerURL

**Comment by lowrisk75** [comment]
Yes I forgot the URL.. thanks a lot.
