### ISSUE TITLE
Wrong IP addresses in canadianshield-protected-https.mobileconfig

### ISSUE THREAD

**Issue by davidbarach** [paulmillr/encrypted-dns#36]
The IP addresses in [canadianshield-protected-https.mobileconfig](https://github.com/paulmillr/encrypted-dns/blob/master/canadianshield-protected-https.mobileconfig) currently end in 10 when they should all end in 20 per the instructions on the [Canadian Shield website](https://www.cira.ca/cybersecurity-services/canadian-shield). 

I checked all the other mobileconfig files for Canadian Shield, and they have the right IP addresses.

Thanks for posting these mobileconfig files for us Canadians!

**Comment by BirdInFire** [comment]
It seem to be patched (this issue can be closed no ?) @paulmillr
