### ISSUE TITLE
How to install on iOS?

### ISSUE THREAD

**Issue by spiritloveroot** [paulmillr/encrypted-dns#43]
This is my first time trying to download something from GitHub on iOS so maybe I'm just missing something easy. I tried to follow the instructions but didn't see any "raw" button to download. I will attach a video screenshare to show what I did...https://user-images.githubusercontent.com/13949350/124803075-44ba3900-df1e-11eb-9157-246a92bcc7fc.MOV

**Comment by paulmillr** [comment]
Fixed - see README now
