### ISSUE TITLE
Why does it say "Not Running" even though I already installed the profile.

### ISSUE THREAD

**Issue by ArrowNemesis** [paulmillr/encrypted-dns#46]

**Comment by ArrowNemesis** [comment]
I'm on macOS Big Sur 11.15.1

**Comment by ArrowNemesis** [comment]
<img width="168" alt="image1" src="https://user-images.githubusercontent.com/77384192/127258015-c4a801d7-ffe5-4538-8bee-ddd54d30fc1f.png">
<img width="369" alt="image2" src="https://user-images.githubusercontent.com/77384192/127258021-fcfb8220-2dde-4b85-85c7-388bcc0ce5f3.png">
<img width="411" alt="image3" src="https://user-images.githubusercontent.com/77384192/127258024-d12482e4-1bfb-4d25-8341-921a51b081ea.png">

**Comment by ArrowNemesis** [comment]
How do you know whether the profile is working or not.

**Comment by zecanard** [comment]
Do you have the option to **Make Service Active**?

<img width="273" alt="Screenshot 2021-07-27 at 23 04 01" src="https://user-images.githubusercontent.com/25799849/127261809-ca45dc57-99a3-4c71-9db2-d8b63049c9d9.png">

**Comment by paulmillr** [comment]
use `tcpdump` to verify it

**Comment by ArrowNemesis** [comment]
> use `tcpdump` to verify it

ok all good thanks for the help
