### ISSUE TITLE
Cannot delete the Cloudflare DNS Option. The minus is greyed out. please help.

### ISSUE THREAD

**Issue by ArrowNemesis** [paulmillr/encrypted-dns#49]
<img width="175" alt="image" src="https://user-images.githubusercontent.com/77384192/127411363-338eb156-92f1-4b75-9541-6e11f34c0f61.png">

**Comment by ArrowNemesis** [comment]
I also went into profiles and it's not there anymore

**Comment by ArrowNemesis** [comment]
how do you delete this thanks.

**Comment by paulmillr** [comment]
we're not tech support, sorry

**Comment by factorin-j** [comment]
@ArrowNemesis cc @paulmillr 
I experience this as well. What I did is temporarily disable SIP and remove `com.apple.networkextension.plist` file, then enable SIP again. You can follow the instructions below:

1. Restart macbook
2. Press `CMD + R` before startup to enter recovery mode.
3. Once entered, open terminal by clicking Utilities > Terminal from the top menu
4. Type `csrutil disable` and hit enter.
5. Restart again proceed to login normally.
6. Open terminal or finder then delete `com.apple.networkextension.plist` from `/Library/Preferences/` folder.

Once deleted, you can check network preference again to see if the service now removed. After that, I suggest that you enable SIP again. Just change the terminal command to `csrutil enable`. This worked for me but please be noted that i'm not a professional and i'm not sure if this might affect or break something on your system. Do it at your own risk.

**Comment by paulmillr** [comment]
You need to delete it from profiles, not from any other place.

**Comment by factorin-j** [comment]
@paulmillr yes. that is what I did first. But I noticed that preference in the network is still there, even if the profile was already deleted just like in the screenshot he provided. BTW, I used the signed config file. Im not sure if this is a bug in BigSur or maybe I messed something up. Im just sharing what I did incase someone other than us experience this.

**Comment by ArrowNemesis** [comment]
@factorin-j  thank you sooo much for the help!

**Comment by ArrowNemesis** [comment]
> @paulmillr yes. that is what I did first. But I noticed that preference in the network is still there, even if the profile was already deleted just like in the screenshot he provided. BTW, I used the signed config file. Im not sure if this is a bug in BigSur or maybe I messed something up. Im just sharing what I did incase someone other than us experience this.

indeed. thanks for that! paul is just arrogant idk not a compliment sorry.

**Comment by paulmillr** [comment]
@ArrowNemesis i'm arrogant because I receive too many free support requests for this stuff from people who don't know what they're doing. Literally, requesting me to spend my time on their issues. On twitter, email, etc. So arrogance is my default reaction these days. 

If you have a real bug, that's a different story.

**Comment by BirdInFire** [comment]
@paulmillr Actually it's a bug of Mac OS (I thinks known but not quite sure). if you remove the profile but cancel when he check your admin access it lead to this bug, no profile but the network one always here, so you have to manually remove the file.
But I do understand your position trough.
