### ISSUE TITLE
Add profiles for Cleanbrowsing servers

### ISSUE THREAD

**Issue by wesinator** [paulmillr/encrypted-dns#50]
Thanks for making these 

Can you add profiles for the Cleanbrowsing servers? 
https://cleanbrowsing.org/filters/ 

I was going to make a PR, but I see the mobileconfig files have some fields like UUIDs in them. 
Do you have a script or something you use to generate profiles ? 

Thanks,

**Comment by paulmillr** [comment]
Use iMazing Profile Editor

**Comment by paulmillr** [comment]
And edit them manually.
