### ISSUE TITLE
Add quad 9 With ECS + quad9 correction

### ISSUE THREAD

**Issue by BirdInFire** [paulmillr/encrypted-dns#56]
I create this issue to correct Quad9 (now in Swiss) and add ECS version
Pull Request come in 5 minutes.

**Comment by BirdInFire** [comment]
If merged can I ask about a version signed ? thanks @paulmillr

**Comment by paulmillr** [comment]
I don't sign it, ask the one who did in readme

**Comment by BirdInFire** [comment]
@paulmillr sure will wait to see if it merged, and if it is I will ask him (not ask to sign something even before knowing if it will be merged ^^)

**Comment by BirdInFire** [comment]
@Candygoblen123 Is it possible to signe the new quad9 (with ecs) who is now merged ?
