### ISSUE TITLE
Blog post doesn't take into account TLS Server Name Indication means middlemen can still see hostnames

### ISSUE THREAD

**Issue by andytson** [paulmillr/encrypted-dns#6]
>With Encrypted DNS, the middlemen will only see 91.198.174.192 — which is an IP of wikipedia.org. Hold on, there’s a nice detail. Ipinfo.org tells us there are at least 19 domain names associated with this IP! In fact, you could be visiting invoker.com — which has the same IP today. The ISP would not know the difference.

The ISP will be able to (with a bit more difficulty) see the TLS ~~ALPN~~ SNI hostname sent plaintext, which all major browsers and some clients will send, however it is still correct the DNS itself would not be susceptible.

**Comment by paulmillr** [comment]
Seems like alpn is not deployed widely yet?

**Comment by paulmillr** [comment]
Can you shed some light on it? How does a packet with alpn look like? Is it always used by webservers?

**Comment by andytson** [comment]
Sorry my mistake, it's the Server Name Indication extension, though both extensions send their data in the ClientHello message before any negotiation of protocols/other extensions. That means they'd be sent even if not supported by the server

**Comment by paulmillr** [comment]
there's encrypted SNI though, a part of tls 1.3

**Comment by andytson** [comment]
yes, though TLS 1.3 not deployed everywhere (though granted Cloudflare makes up a lot for that)

**Comment by paulmillr** [comment]
That's what makes deep packet inspection much more useful afaik. Sad!

**Comment by paulmillr** [comment]
updated my blog post to mention sni

**Comment by andytson** [comment]
It seems TLS 1.3 doesn't natively imply encrypted SNI either, and requires a DNS text record for the ESNI public key.
