### ISSUE TITLE
Please add Nextdns TLS/HTTPS with custom id profiles

### ISSUE THREAD

**Issue by frykauf** [paulmillr/encrypted-dns#63]
Because their profiles suck, don’t even import and don’t have support for DOH/DOT.

Thankfully macOS can just add the VPN profile from the macOS app and connect from Network setting without the app after but I don’t think iOS is as lucky.

Plus would be cool if I could edit the profile myself and choose preferred DNS server since their 2nd backup one is usually like 2x as fast or more — though I don’t know if that would work with their custom ID DNS profile for dashboard/filters and whatnot.

**Comment by paulmillr** [comment]
Add it by yourself.

**Comment by BirdInFire** [comment]
@paulmillr close this one, he ask something they already have done themselves : "https://apple.nextdns.io" it seem this one does not even have done a google search
