### ISSUE TITLE
OpenDNS Family Shield

### ISSUE THREAD

**Issue by Gondi67** [paulmillr/encrypted-dns#8]
The script published for adding OpenDNS servers to iOS 14.x devices only supports the OpenDNS Home servers. For OpenDNS Family Shield users the following OpenDNS IP addresses must be configured on the iOS 14.x devices.

![image](https://user-images.githubusercontent.com/73424450/97104532-df3a5b00-16b4-11eb-96d9-16cb3a372c5d.png)

Please visit https://en.wikipedia.org/wiki/OpenDNS or https://support.opendns.com/hc/en-us/articles/227988127-Getting-started-About-using-OpenDNS for more information.

**Comment by paulmillr** [comment]
- [ ]
