### ISSUE TITLE
Censorship emojis are unclear

### ISSUE THREAD

**Issue by joelmellon** [paulmillr/encrypted-dns#93]
It's not clear what the red/green emojis mean under censorship.

<img width="465" alt="Screen Shot 2022-04-18 at 10 01 56 AM" src="https://user-images.githubusercontent.com/13803216/163844267-45a53f9e-faec-48fb-a211-fd8ad593382d.png">
 
1. Is censorship even the right word? How about "Filtering"?
2. Can you simply write "Yes" and "No"?

**Comment by paulmillr** [comment]
Improved
