### ISSUE TITLE
update dnspod DoH DNS

### ISSUE THREAD

**Issue by xunichanghuan** [paulmillr/encrypted-dns#99]
https://120.53.53.53/dns-query
https://1.12.12.12/dns-quer
![DoH](https://user-images.githubusercontent.com/9484015/172043387-3d9997b2-fa01-4849-9b9a-08ead4be97cb.png)

**Comment by paulmillr** [comment]
Why are you wasting maintainer's time by posting random sites? https://docs.dnspod.cn/public-dns/dot-doh/ clearly says the address is `https://doh.pub/dns-query`, and pinging the url gives `162.14.21.178`

**Comment by xunichanghuan** [comment]
In China, 1.12.12.12 and 120.53.53.53 are significantly faster
![20220605175650](https://user-images.githubusercontent.com/9484015/172045093-5cd9a7d5-53e1-464a-8c58-229c93f31a57.png)

**Comment by paulmillr** [comment]
So what? The sites could be hacker's attempt to hijack dnspod. How do you know it's authentic? The official site says nothing about the IP addresses.

**Comment by xunichanghuan** [comment]
![doh pub_多地Ping值测试](https://user-images.githubusercontent.com/9484015/172053724-b58a65eb-1bd1-4c38-88c3-cfe1253172b1.png)

**Comment by paulmillr** [comment]
I don't know chinese, and I don't care about screenshots. Point me to a documentation on their site.

**Comment by xunichanghuan** [comment]
https://www.dnspod.cn/Products/Public.DNS?lang=en
On this page, we can find DOH (IP)
